-- Migration v2: 使用 Stored Procedure 實現 MySQL 相容的 IF NOT EXISTS 欄位新增

DROP PROCEDURE IF EXISTS run_migration_v2;

DELIMITER //

CREATE PROCEDURE run_migration_v2()
BEGIN
    -- 1. USER 表：新增 skill_levels
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USER' AND COLUMN_NAME = 'skill_levels'
    ) THEN
        ALTER TABLE USER ADD COLUMN skill_levels JSON DEFAULT NULL;
    END IF;

    -- 2. WORKOUTINVITATION 表：新增經緯度與技能等級
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND COLUMN_NAME = 'latitude'
    ) THEN
        ALTER TABLE WORKOUTINVITATION ADD COLUMN latitude DECIMAL(10, 8) DEFAULT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND COLUMN_NAME = 'longitude'
    ) THEN
        ALTER TABLE WORKOUTINVITATION ADD COLUMN longitude DECIMAL(11, 8) DEFAULT NULL;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND COLUMN_NAME = 'required_skill_level'
    ) THEN
        ALTER TABLE WORKOUTINVITATION ADD COLUMN required_skill_level INT DEFAULT 1;
    END IF;

    -- 3. 新增空間座標欄位（Generated Column，依賴 latitude/longitude 先存在）
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND COLUMN_NAME = 'location_point'
    ) THEN
        ALTER TABLE WORKOUTINVITATION
        ADD COLUMN location_point POINT AS (
            ST_PointFromText(CONCAT('POINT(', COALESCE(longitude, 0), ' ', COALESCE(latitude, 0), ')'), 4326)
        ) STORED NULL;
    END IF;

    -- 4. 空間索引與查詢索引
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND INDEX_NAME = 'idx_invitation_location'
    ) THEN
        ALTER TABLE WORKOUTINVITATION ADD SPATIAL INDEX idx_invitation_location (location_point);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND INDEX_NAME = 'idx_invitation_time'
    ) THEN
        ALTER TABLE WORKOUTINVITATION ADD INDEX idx_invitation_time (event_time);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'WORKOUTINVITATION' AND INDEX_NAME = 'idx_invitation_skill'
    ) THEN
        ALTER TABLE WORKOUTINVITATION ADD INDEX idx_invitation_skill (required_skill_level);
    END IF;

    -- 5. INVITATIONPARTICIPANT 表：新增候補狀態欄位
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'INVITATIONPARTICIPANT' AND COLUMN_NAME = 'status'
    ) THEN
        ALTER TABLE INVITATIONPARTICIPANT
        ADD COLUMN status ENUM('confirmed', 'waitlisted', 'cancelled') DEFAULT 'confirmed';
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'INVITATIONPARTICIPANT' AND INDEX_NAME = 'idx_participant_status'
    ) THEN
        ALTER TABLE INVITATIONPARTICIPANT ADD INDEX idx_participant_status (status);
    END IF;

    -- 6. 動態牆效能優化索引
    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'POST' AND INDEX_NAME = 'idx_post_feed'
    ) THEN
        ALTER TABLE POST ADD INDEX idx_post_feed (board_id, created_at);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM INFORMATION_SCHEMA.STATISTICS
        WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'COMMENT' AND INDEX_NAME = 'idx_comment_lookup'
    ) THEN
        ALTER TABLE COMMENT ADD INDEX idx_comment_lookup (post_id, created_at);
    END IF;

END //

DELIMITER ;

CALL run_migration_v2();
DROP PROCEDURE IF EXISTS run_migration_v2;
